services:
  jtrial:
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${BUILD_CONTEXT}/${REL_DNODEJ_LOC}/docker/juliatrial-file
      args:
        REL_SCRIBE_LOC: ${REL_SCRIBE_LOC}
        REL_DNODEJ_LOC: ${REL_DNODEJ_LOC}
    container_name: jtrial

  r2base:
    image: dnode_api:r2base
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${BUILD_CONTEXT}/${REL_DNODEJ_LOC}/docker/r2julia-file
      args:
        ROS_DISTRO: humble
        REL_DNODEJ_LOC: ${REL_DNODEJ_LOC}
        REL_SCRIBE_LOC: ${REL_SCRIBE_LOC}
      target: r2base
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority

  r2overlay:
    extends: r2base
    image: dnode_api:r2overlay
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${BUILD_CONTEXT}/${REL_DNODEJ_LOC}/docker/r2julia-file
      args:
        UID: ${UID:-1000}
        GID: ${UID:-1000}
        USERNAME: ${USERNAME:-devuser}
      target: r2overlay
    user: ${USERNAME:-devuser}

  r2dev:
    extends: r2overlay
    image: dnode_api:r2dev
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${BUILD_CONTEXT}/${REL_DNODEJ_LOC}/docker/r2julia-file
      target: r2dev
    stdin_open: true
    tty: true
    ports:
      - "5000:5555"
      - "2222:22"
    privileged: true
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      # Mount the source code
      - ${BUILD_CONTEXT}/${REL_DNODEJ_LOC}:/dnode/src/dNodeJ:rw
      - ${BUILD_CONTEXT}/${REL_SCRIBE_LOC}:/dnode/src/SCRIBE:rw
      # Mount colcon build artifacts for faster rebuilds
      - ${BUILD_CONTEXT}/${REL_DNODEJ_LOC}/.colcon/build/:/dnode/build/:rw
      - ${BUILD_CONTEXT}/${REL_DNODEJ_LOC}/.colcon/install/:/dnode/install/:rw
      - ${BUILD_CONTEXT}/${REL_DNODEJ_LOC}/.colcon/log/:/dnode/log/:rw
      # To do some easy container-to-container discussions (bad)
      - /dev/shm:/dev/shm:rw
    user: ${USERNAME:-devuser}
    command: bash # sudo /usr/sbin/sshd -D

  colcon:
    extends: r2dev
    command: colcon build